more resilience in make deps

diff --git a/bin/do-install-deps b/bin/do-install-deps
--- a/bin/do-install-deps
+++ b/bin/do-install-deps
@@ -4,27 +4,34 @@ depslist=$(< build-deps )
 
 if which apt-get && ! -f /etc/redhat-release
 then
+  echo "I suspect your machine is Debian."
   # Probably Debian, not Fedora/Red Hat.
   # Use alternative package names.
   depslist=$( sed build-deps -e 's,^nodejs-,node-,g' )
+else
+  echo "I hope your machine is a Fedora/Red Hat family member"
 fi
 
 if which pkcon
 then
+  echo "Oh, good. I see you have PackageKit."
   if pkcheck -a org.freedesktop.packagekit.package-install-untrusted -p $$$$
   then
     for pkg in $depslist
     do
-      pkcon -y install $pkg
+      pkcon -p -y install $pkg
     done
   else 
     for pkg in $depslist
     do
-      sudo pkcon -y install $pkg
+      sudo pkcon -p -y install $pkg
     done
   fi
+  true
   exit
 fi
+
+echo "PackageKit not found."
 
 if which dnf
 then 
@@ -44,4 +51,13 @@ then
   do
     sudo apt-get -y install $pkg
   done
+else
+  echo "Unable to find a usable alternative to PackageKit." >&2
+  echo "You'll need to install these dependencies yourself:"
+  echo "———"
+  cat build-deps
+  false
+  exit 1
 fi
+
+true
