prettier server push

diff --git a/server-push b/server-push
--- a/server-push
+++ b/server-push
@@ -1,29 +1,65 @@
-#!/bin/bash -xe
+#!/bin/bash -e
+
+BOLD=" ★ "
+
+if [ -t ]
+then
+    BOLD="[1;32m ★ [0m[1m"
+fi
+
+NORM="[0m"
+
+RSYNC=rsync -essh -v --timeout=45
+
+echo $BOLD Building assets $NORM
 make assets
 
-rsync -essh -rv static src templates \
-      tootstest.asd *.lisp \
+echo $BOLD Synchronizing assets and source to host $NORM
+$RSYNC -r static src templates \
+      tootstest.asd Makefile *.lisp \
       .htaccess robots.txt \
+      --exclude '*~' --exclude '.#*' \
+      --exclude 'src/lib/babylon.js/**' \
       tootsville.adventuring.click:tootsville.adventuring.click/
 
-rsync -essh -rv tootsville.org/error \
+echo $BOLD Synchronizing error pages with Tootsville.org $NORM
+$RSYNC -r tootsville.org/error \
       tootsville.adventuring.click:tootsville.adventuring.click/
 
+echo $BOLD Pushing Tootsville.org web site $NORM
+$RSYNC -r tootsville.org tootsvilleorg@tootsville.org:
+
+echo $BOLD Building local executable to test $NORM
 make tootstest.cgi
 
-scp tootstest.asd Makefile app.lisp tootsville.adventuring.click:tootsville.adventuring.click/
-rsync -essh -v bin/* tootsville.adventuring.click:tootsville.adventuring.click/bin/
+echo $BOLD Pushing bin/ scripts $NORM
+$RSYNC bin/* tootsville.adventuring.click:tootsville.adventuring.click/bin/
 
-for build_try in 1 2 3
+echo $BOLD Attempting to build on host $NORM
+build_tries=5
+build_try=1
+while [ $build_try -lt $build_tries ]
 do
-    ssh tootsville.adventuring.click make -C tootsville.adventuring.click tootstest.cgi || (
-        echo " Build attempt failed: try $build_try of 3."
-        sleep 30
+    ssh tootsville.adventuring.click nice make -C tootsville.adventuring.click tootstest.cgi || (
+        echo "$BOLD Build attempt failed: try $build_try of $build_tries.$NORM"
+        if [ $build_try -lt $build_tries ]
+        then
+            delay=$(( $build_try * 30 ))
+            echo $BOLD will try again in $delay sec $NORM
+            sleep $delay
+            build_try=$(( 1 + $build_try ))
+        else
+            echo $BOLD Exhausted build attempts, aborting $NORM
+            exit -5
+        fi
     )
 done
 
-rsync -essh -rv tootsville.org tootsvilleorg@tootsville.org:
+echo $BOLD Tagging pushed release $NORM
+git tag -s server-push-$(date +%Y-%m-%d-%H%M) HEAD \
+    -m "Pushed to server from $(whoami)@$(hostname) at $(date); $(git status -s -uno)"
 
+echo $BOLD Waiting for FastCGI to refresh $NORM
 until curl https://tootsville.adventuring.click/version.txt 2>/dev/null | \
         grep -E "^Build-Date:\s+$( date +%Y-%m-%d | sed -e s/-0/-/g )"
 do
@@ -31,7 +67,7 @@ do
 	sleep 30 
 done
 
-# Notify Rollbar of the deployment
+echo $BOLD Notifying Rollbar of the deployment $NORM
 curl https://api.rollbar.com/api/1/deploy/ \
      -F access_token=f6f4ae4d08dd415799a1ef2122fff0b0 \
      -F environment=$(./tootstest.cgi version-info product) \
@@ -39,7 +75,7 @@ curl https://api.rollbar.com/api/1/deploy/ \
      -F version=$(./tootstest.cgi version-info version) \
      -F local_username="$(whoami)%$(hostname)"
 
-# Provide Source Maps to Rollbar
+# echo $BOLD Providing Source Maps to Rollbar $NORM
 # curl https://api.rollbar.com/api/1/sourcemap \
 #   -F access_token=aaaabbbbccccddddeeeeffff00001111 \
 #   -F version=version_string_here \
@@ -47,7 +83,4 @@ curl https://api.rollbar.com/api/1/deploy/ \
 #   -F source_map=@static/js/example.min.map \
 #   -F static/js/site.js=@static/js/site.js \
 #   -F static/js/util.js=@static/js/util.js
-
-git tag -s server-push-$(date +%Y-%m-%d-%H%M) HEAD \
-    -m "Pushed to server from $(who am i)@$(hostname) at $(date); $(git status -s -uno)"
 
