misc futzing with version, maintenance

diff --git a/server-push b/server-push
--- a/server-push
+++ b/server-push
@@ -1,23 +1,28 @@
 #!/bin/bash -xe
 make assets
 
-rsync -essh -rv static tootstest.asd *.lisp .htaccess robots.txt templates \
-	tootsville.adventuring.click:tootsville.adventuring.click/
+rsync -essh -rv static/ src/ templates/ \
+      tootstest.asd *.lisp \
+      .htaccess robots.txt \
+      tootsville.adventuring.click:tootsville.adventuring.click/
 
 make tootstest.cgi
 
 scp tootstest.asd Makefile app.lisp tootsville.adventuring.click:tootsville.adventuring.click/
 rsync -essh -v bin/* tootsville.adventuring.click:tootsville.adventuring.click/bin/
-rsync -essh -v src/*.lisp tootsville.adventuring.click:tootsville.adventuring.click/src/
 
-ssh tootsville.adventuring.click make -C tootsville.adventuring.click tootstest.cgi
+for build_try in 1 2 3
+do
+    ssh tootsville.adventuring.click make -C tootsville.adventuring.click tootstest.cgi || (
+        echo " Build attempt failed: try $build_try of 3."
+        sleep 30
+    )
+done
 
 rsync -essh -rv tootsville.org tootsvilleorg@tootsville.org:
 
-until curl -H 'Accept: text/html' \
-           https://tootsville.adventuring.click/version 2>/dev/null | \
-	perl -ne 'if (/build-date">(20..-..?-..?)</) {print $1}' | \
-	grep $( date +%Y-%m-%d | sed -e s/-0/-/g )
+until curl https://tootsville.adventuring.click/version.txt 2>/dev/null | \
+        grep -E "^Build-Date:\s+$( date +%Y-%m-%d | sed -e s/-0/-/g )"
 do
 	echo "New version not yet running (FastCGI cache?)"
 	sleep 30 
